services:
  - type: web
    name: techabout-donation-tool
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: TARGET_AMOUNT
        value: 100000
